name: BiraloVPS 24/7 Auto Backup

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'  # Runs every 6 hours automatically

jobs:
  tmate-session:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y tmate curl tar

    - name: Restore backup
      run: |
        chmod +x ./backup-restore.sh
        ./backup-restore.sh restore_backup || echo "No backup found."

    - name: Start tmate session and keep alive for 6 hours
      run: |
        # Start tmate session in background, output logs
        tmate -F | tee session.log &

        # Wait for tmate session to fully initialize
        sleep 15

        # Show the session connection links in logs
        grep -E 'ssh|https://tmate.io' session.log

        # Keep workflow alive for 6 hours so session stays alive
        sleep 21600

    - name: Backup data before shutdown
      run: |
        ./backup-restore.sh backup_and_upload || echo "Backup failed."
