name: Biralo Cloud VPS

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'  # Restart every 6 hours

jobs:
  vps:
    runs-on: ubuntu-latest

    steps:
    - name: Setup cloudflared + install server
      run: |
        # Install basic tools
        sudo apt update
        sudo apt install -y curl unzip python3

        # Start simple HTTP server on port 8080
        nohup python3 -m http.server 8080 &

        # Download & start Cloudflare tunnel
        curl -L https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64 -o cloudflared
        chmod +x cloudflared

        # Start tunnel
        ./cloudflared tunnel --url http://localhost:8080
