name: BiraloCloud Web Terminal

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'

jobs:
  vps:
    runs-on: ubuntu-latest
    steps:
    - name: Install ttyd and cloudflared
      run: |
        sudo apt update
        sudo apt install -y cmake g++ libjson-c-dev libwebsockets-dev git curl unzip

        git clone https://github.com/tsl0922/ttyd.git
        cd ttyd
        mkdir build && cd build
        cmake ..
        make
        sudo make install
        cd ~

        # Start ttyd (web terminal) on port 8080
        nohup ttyd bash &

        # Download & run Cloudflared
        curl -L https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64 -o cloudflared
        chmod +x cloudflared
        ./cloudflared tunnel --url http://localhost:8080
