name: BiraloVPS 24/7

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'  # Every 6 hours auto restart

jobs:
  run-vps:
    runs-on: ubuntu-latest
    steps:
    - name: Setup and start Cloudflared VPS
      run: |
        sudo apt update
        sudo apt install -y curl unzip
        curl -LO https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64
        chmod +x cloudflared-linux-amd64
        ./cloudflared-linux-amd64 tunnel --url http://localhost:8080
