name: BiraloVPS 24/7 Auto Backup

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'  # Auto restart every 6 hours

jobs:
  tmate-session:
    runs-on: ubuntu-latest

    steps:
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y tmate curl tar

    - name: Restore backup, start tmate, and auto backup
      run: |
        chmod +x ./backup-restore.sh
        ./backup-restore.sh restore_backup || echo "No backup found."

        # Start tmate in background, logs saved
        tmate -F | tee session.log &

        # Wait a bit for tmate to start
        sleep 30

        # Backup current data before workflow ends
        ./backup-restore.sh backup_and_upload || echo "Backup failed."

    - name: Show session links
      run: grep -E 'ssh|https://tmate.io' session.log
